Allow the 'expose_php' setting to be configured.
zivtech/puppet-drupal-php pull request #11
Opened 2016-12-07 15:19 UTC by lliss

A nice security hardening measure is setting 'expose_php' to
'Off' in the apache php.ini file. This prevents the returned
headers from revealing information about PHP and the server
version information. Previously it was not possible to set this
through the drupal-php module since the option in the required
php module required further configuration.

2016-12-07 20:57 UTC, tizzo requested changes
In theory we are going to support nginx/phpfpm at some point so I think the apache conf should move to the apache class.

2016-12-07 20:57 UTC, tizzo commented on manifests/init.pp
> +  php::apache::config { 'php-expose-php':
This should be moved into the apache server class.

2016-12-07 21:23 UTC, lliss commented on manifests/init.pp
> +  php::apache::config { 'php-expose-php':
It seemed this should live with all the other options that also are structured the same way. The apache server class does not contain any of the php apache config.

2016-12-08 13:40 UTC, lliss commented
I've opened a new issue for refactoring this since it really is a more significant issue.
https://github.com/zivtech/puppet-drupal-php/issues/12
I'm going to suggest we merge this as it is since it continues to group the apache config settings together and we can move them all at once later.

2017-01-09 13:59 UTC, merged